/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;


import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;


/**
 *
 * @author A. Alharbi
 */
public class Add_Employee extends javax.swing.JFrame {

    /**
     * Creates new form Add_Employee
     */
    public Add_Employee() {
        initComponents();
    }
    ManagerOption ManagerOption = new ManagerOption();

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jPanel2 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        Username_jTextField1 = new javax.swing.JTextField();
        Password_jTextField2 = new javax.swing.JTextField();
        Id_jTextField3 = new javax.swing.JTextField();
        Fname_jTextField4 = new javax.swing.JTextField();
        Lname_jTextField5 = new javax.swing.JTextField();
        Hours_jTextField6 = new javax.swing.JTextField();
        jLabel8 = new javax.swing.JLabel();
        Address_jTextField7 = new javax.swing.JTextField();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        Age_jTextField8 = new javax.swing.JTextField();
        Email_jTextField9 = new javax.swing.JTextField();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jLabel14 = new javax.swing.JLabel();
        jLabel15 = new javax.swing.JLabel();
        salaryPerHour_jTextField10 = new javax.swing.JTextField();
        MAG_ID_jTextField11 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(null);

        jPanel2.setBackground(new java.awt.Color(102, 51, 0,80
        ));
        jPanel2.setForeground(new java.awt.Color(255, 255, 255));

        jLabel2.setFont(new java.awt.Font("Stencil", 0, 16)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(255, 255, 255));
        jLabel2.setText("ID");

        jLabel3.setFont(new java.awt.Font("Stencil", 0, 16)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("First Name");

        jLabel4.setFont(new java.awt.Font("Stencil", 0, 16)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("Last Name");

        jLabel5.setFont(new java.awt.Font("Stencil", 0, 16)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(255, 255, 255));
        jLabel5.setText("working hours");

        jLabel6.setFont(new java.awt.Font("Stencil", 0, 16)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(255, 255, 255));
        jLabel6.setText("Address");

        jLabel7.setFont(new java.awt.Font("Stencil", 0, 16)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(255, 255, 255));
        jLabel7.setText("Age");

        Username_jTextField1.setBackground(new java.awt.Color(255, 250, 243));
        Username_jTextField1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Username_jTextField1.setForeground(new java.awt.Color(101, 58, 15));
        Username_jTextField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(101, 58, 15), 3, true));

        Password_jTextField2.setBackground(new java.awt.Color(255, 250, 243));
        Password_jTextField2.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Password_jTextField2.setForeground(new java.awt.Color(101, 58, 15));
        Password_jTextField2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(101, 58, 15), 3, true));

        Id_jTextField3.setBackground(new java.awt.Color(255, 250, 243));
        Id_jTextField3.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Id_jTextField3.setForeground(new java.awt.Color(101, 58, 15));
        Id_jTextField3.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(101, 58, 15), 3, true));

        Fname_jTextField4.setBackground(new java.awt.Color(255, 250, 243));
        Fname_jTextField4.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Fname_jTextField4.setForeground(new java.awt.Color(101, 58, 15));
        Fname_jTextField4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(101, 58, 15), 3, true));

        Lname_jTextField5.setBackground(new java.awt.Color(255, 250, 243));
        Lname_jTextField5.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Lname_jTextField5.setForeground(new java.awt.Color(101, 58, 15));
        Lname_jTextField5.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(101, 58, 15), 3, true));

        Hours_jTextField6.setBackground(new java.awt.Color(255, 250, 243));
        Hours_jTextField6.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Hours_jTextField6.setForeground(new java.awt.Color(101, 58, 15));
        Hours_jTextField6.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(101, 58, 15), 3, true));

        jLabel8.setFont(new java.awt.Font("Stencil", 0, 16)); // NOI18N
        jLabel8.setForeground(new java.awt.Color(255, 255, 255));
        jLabel8.setText("Email");

        Address_jTextField7.setBackground(new java.awt.Color(255, 250, 243));
        Address_jTextField7.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Address_jTextField7.setForeground(new java.awt.Color(101, 58, 15));
        Address_jTextField7.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(101, 58, 15), 3, true));

        jLabel10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/logo2.png"))); // NOI18N

        jLabel11.setFont(new java.awt.Font("Vivaldi", 1, 36)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(255, 255, 255));
        jLabel11.setText("Add Employee");

        jButton1.setBackground(new java.awt.Color(255, 250, 243));
        jButton1.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(101, 58, 15));
        jButton1.setText("Add");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(101, 58, 15), 3, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setBackground(new java.awt.Color(255, 250, 243));
        jButton2.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(101, 58, 15));
        jButton2.setText("Back");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(101, 58, 15), 3, true));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        Age_jTextField8.setBackground(new java.awt.Color(255, 250, 243));
        Age_jTextField8.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Age_jTextField8.setForeground(new java.awt.Color(101, 58, 15));
        Age_jTextField8.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(101, 58, 15), 3, true));

        Email_jTextField9.setBackground(new java.awt.Color(255, 250, 243));
        Email_jTextField9.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        Email_jTextField9.setForeground(new java.awt.Color(101, 58, 15));
        Email_jTextField9.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(101, 58, 15), 3, true));

        jLabel12.setFont(new java.awt.Font("Stencil", 0, 16)); // NOI18N
        jLabel12.setForeground(new java.awt.Color(255, 255, 255));
        jLabel12.setText("Username");

        jLabel13.setFont(new java.awt.Font("Stencil", 0, 16)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(255, 255, 255));
        jLabel13.setText("Password");

        jLabel14.setFont(new java.awt.Font("Stencil", 0, 16)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("salary per hour");

        jLabel15.setFont(new java.awt.Font("Stencil", 0, 16)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(255, 255, 255));
        jLabel15.setText("Manager ID");

        salaryPerHour_jTextField10.setBackground(new java.awt.Color(255, 250, 243));
        salaryPerHour_jTextField10.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        salaryPerHour_jTextField10.setForeground(new java.awt.Color(101, 58, 15));
        salaryPerHour_jTextField10.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(101, 58, 15), 3, true));

        MAG_ID_jTextField11.setBackground(new java.awt.Color(255, 250, 243));
        MAG_ID_jTextField11.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        MAG_ID_jTextField11.setForeground(new java.awt.Color(101, 58, 15));
        MAG_ID_jTextField11.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(101, 58, 15), 3, true));

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(38, 38, 38)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jLabel10)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel9)
                        .addGap(7, 7, 7)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 294, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(1, 1, 1)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel4)
                                            .addComponent(jLabel3)
                                            .addComponent(jLabel7)))
                                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                        .addComponent(jLabel13)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(jLabel12)
                                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                                .addComponent(jLabel2)
                                                .addGap(66, 66, 66)))))
                                .addGap(55, 55, 55)
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(Username_jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Password_jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Fname_jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Id_jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Lname_jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(Age_jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                            .addComponent(jButton2, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(58, 58, 58)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel14)
                                    .addComponent(jLabel6)
                                    .addComponent(jLabel8)
                                    .addComponent(jLabel15))
                                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addGroup(jPanel2Layout.createSequentialGroup()
                                        .addGap(29, 29, 29)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                            .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                                .addComponent(Email_jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                                .addComponent(jButton1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 125, javax.swing.GroupLayout.PREFERRED_SIZE))
                                            .addComponent(Address_jTextField7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))
                                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                            .addComponent(salaryPerHour_jTextField10, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)
                                            .addComponent(MAG_ID_jTextField11, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                            .addGroup(jPanel2Layout.createSequentialGroup()
                                .addComponent(jLabel5)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(Hours_jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, 149, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap(38, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(40, 40, 40)
                        .addComponent(jLabel9))
                    .addComponent(jLabel10, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jLabel11, javax.swing.GroupLayout.PREFERRED_SIZE, 69, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Username_jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel12)
                    .addComponent(jLabel8)
                    .addComponent(Email_jTextField9, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 27, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Password_jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel13)
                    .addComponent(jLabel6)
                    .addComponent(Address_jTextField7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(38, 38, 38)
                        .addComponent(jLabel2))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(28, 28, 28)
                        .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(Id_jTextField3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(jLabel5)
                            .addComponent(Hours_jTextField6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 36, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Fname_jTextField4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel3)
                    .addComponent(jLabel14)
                    .addComponent(salaryPerHour_jTextField10, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(34, 34, 34)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(Lname_jTextField5, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel4)
                    .addComponent(jLabel15)
                    .addComponent(MAG_ID_jTextField11, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(24, 24, 24)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel7)
                    .addComponent(Age_jTextField8, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 65, Short.MAX_VALUE)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton1)
                    .addComponent(jButton2))
                .addGap(45, 45, 45))
        );

        jPanel1.add(jPanel2);
        jPanel2.setBounds(90, 20, 750, 570);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/back2.jpg"))); // NOI18N
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 0, 890, 610);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 893, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 610, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        String fname , lname , address , username , password, email;
        double hours = 0.0 , salary_per_hour = 0.0;
        int age = 0  ,eid= 0 ,MAG_ID =0;
        boolean passlowerCase= false , passupperCase=false  , passischar=false , passisDigit=false;
        username = Username_jTextField1.getText() ;
        password = Password_jTextField2.getText();
        fname = Fname_jTextField4.getText();
        lname = Lname_jTextField5.getText();
        address = Address_jTextField7.getText();
        try{
        salary_per_hour = Double.parseDouble(salaryPerHour_jTextField10.getText());
        hours = Double.parseDouble(Hours_jTextField6.getText());
        MAG_ID = Integer.parseInt(MAG_ID_jTextField11.getText());
        age = Integer.parseInt(Age_jTextField8.getText());
        eid = Integer.parseInt(Id_jTextField3.getText());
        } 
        catch(NumberFormatException e)
        {JOptionPane.showMessageDialog(this,"Please enter Age, Salary , manager ID , hours, and your ID in numbers only  "); }
        email = Email_jTextField9.getText();
        
        
        try(Connection connection = DriverManager.getConnection("jdbc:derby://localhost:1527/Cottege_Bakery", "Bakery", "Bakery");
            Statement Add_EmployeeSt = connection.createStatement();
            Statement addEAccountSt = connection.createStatement();   
            Statement getIDStatement = connection.createStatement();
            )
        {
          for(int i=0 ; i<password.length() ;i++)
            {
                if(Character.isDigit(password.charAt(i))){ passisDigit = true ;}
                if(Character.isLowerCase(password.charAt(i))) {passlowerCase = true ;}
                if(Character.isUpperCase(password.charAt(i))){passupperCase = true;}    
            }
            if(password.contains("@") || password.contains("#") || password.contains("&") || password.contains("?")|| password.contains("_")
               ||password.contains(".") || password.contains("<") || password.contains("$")||password.contains(":")) 
            {passischar = true ;}  
           
        if(
                !"".equals(Username_jTextField1.getText()) && !"".equals(Password_jTextField2.getText())
                && !"".equals(Id_jTextField3.getText()) && !"".equals(Fname_jTextField4.getText()) &&!"".equals(Lname_jTextField5.getText())
                && !"".equals(Hours_jTextField6.getText()) && !"".equals(Address_jTextField7.getText()) && !"".equals(Age_jTextField8.getText())
                && !"".equals(salaryPerHour_jTextField10.getText()) && !"".equals(Email_jTextField9.getText()) && !"".equals(MAG_ID_jTextField11.getText())
          ){
            if(password.length() >= 8 && passlowerCase && passupperCase && passischar && passisDigit)
            { 
            int Add_Employee =  Add_EmployeeSt.executeUpdate("INSERT INTO Employee (Employee_ID , Fname , Lname , hours , address , age, salary_per_hour ,mail, MAG_ID) values "
             + "("+eid +",'"+fname+"','"+lname+"',"+hours + ",'" +address+"',"+ age + "," + salary_per_hour + ",'" +email +"'," + MAG_ID +")");
            
             try (ResultSet rs = getIDStatement.executeQuery("SELECT EMPLOYEE_ID FROM Employee WHERE FNAME = '"+fname+"' AND LNAME = '"+lname+"'"))
                {
                    if(rs.next())
                    {
                        eid = rs.getInt(1);
                        
                        int addEmployeeAcc = addEAccountSt.executeUpdate("INSERT INTO Employee_Account (USERNAME , PASSWORD , EID) values "
                                + "('"+username+"','" + password + "',"+eid+")");
                        

                        if(Add_Employee==1 && addEmployeeAcc == 1){
                            JOptionPane.showMessageDialog(this, "Employee added successfully....");
                            // add customer to customer arraylist
                            Project.addEmployee(new Employee(salary_per_hour, hours, address, eid,  fname, lname,  age, username,  password , MAG_ID));
                            reset();
                            this.setVisible(false);
                            ManagerOption.setVisible(true);
                        }
                    }
                    else {JOptionPane.showMessageDialog(this, "Try again");}

                }
            
            } 
             else {
                
                JOptionPane.showMessageDialog(this, "Password should be :\n1- at least 8 length size\n2- Have capital and small letters"
                + "\n3- Password should have numbers\n4- differen characters : (@ , # , & , ? , _ , . , < , $ , :) ");
            }
            
        } 
        else{JOptionPane.showMessageDialog(this, "Fill all the information!..");}
            connection.close();
        
        }catch(SQLException e ){
            JOptionPane.showMessageDialog(this, e.getMessage());

        }
        
        
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        ManagerOption ManagerOption = new ManagerOption();
        this.setVisible(false);
        ManagerOption.setVisible(true);
    }//GEN-LAST:event_jButton2ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Add_Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Add_Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Add_Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Add_Employee.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Add_Employee().setVisible(true);
            }
        });
    }
    public void reset(){
      Username_jTextField1.setText("");
      Password_jTextField2.setText("");
      Id_jTextField3.setText("");
      Fname_jTextField4.setText("");
      Lname_jTextField5.setText("");
      Hours_jTextField6.setText("");
      Address_jTextField7.setText("");
      Age_jTextField8.setText("");
      salaryPerHour_jTextField10.setText("");
      Email_jTextField9.setText("");
      MAG_ID_jTextField11.setText("");
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JTextField Address_jTextField7;
    private javax.swing.JTextField Age_jTextField8;
    private javax.swing.JTextField Email_jTextField9;
    private javax.swing.JTextField Fname_jTextField4;
    private javax.swing.JTextField Hours_jTextField6;
    private javax.swing.JTextField Id_jTextField3;
    private javax.swing.JTextField Lname_jTextField5;
    private javax.swing.JTextField MAG_ID_jTextField11;
    private javax.swing.JTextField Password_jTextField2;
    private javax.swing.JTextField Username_jTextField1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTextField salaryPerHour_jTextField10;
    // End of variables declaration//GEN-END:variables
}
