/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.sql.*;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import project.ModifyOrder;
import project.Order;
import project.Orders;
import project.ShoppingCart;

/**
 *
 * @author Haya alzahim
 */
public class Cake extends javax.swing.JFrame {
String[] cakes={"Cheesecake", "Naked cake", "Sponge cake"};
static String flavor="", toppings="";

/*p.CakekArray*

    /**
     * Creates new form Cake
     */
    public Cake() {
        initComponents();
        this.setVisible(true);
        this.setSize(800,570);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        buttonGroup1 = new javax.swing.ButtonGroup();
        jComboBox1 = new javax.swing.JComboBox<>();
        jButton3 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jRadioButton4 = new javax.swing.JRadioButton();
        jLabel4 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jLabel10 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jComboBox1.setBackground(new java.awt.Color(239, 239, 251));
        jComboBox1.setFont(new java.awt.Font("Lucida Calligraphy", 1, 24)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(101, 58, 15));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Cheesecake", "Naked cake", "Sponge cake" }));
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBox1.setFocusable(false);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(270, 190, 220, 60);

        jButton3.setBackground(new java.awt.Color(255, 250, 243));
        jButton3.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jButton3.setForeground(new java.awt.Color(101, 58, 15));
        jButton3.setText("Back");
        jButton3.setToolTipText("To go back to the previous page");
        jButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton3.setFocusable(false);
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton3);
        jButton3.setBounds(30, 450, 90, 30);

        jButton2.setBackground(new java.awt.Color(255, 250, 243));
        jButton2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/catr-PNG.png"))); // NOI18N
        jButton2.setToolTipText("To go to the shopping cart");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.setFocusable(false);
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(680, 40, 60, 50);

        jButton1.setBackground(new java.awt.Color(255, 250, 243));
        jButton1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(101, 58, 15));
        jButton1.setText("Confirm");
        jButton1.setToolTipText("To confirm your selection");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.setFocusable(false);
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(650, 450, 110, 30);

        jLabel3.setFont(new java.awt.Font("Lucida Calligraphy", 1, 36)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(243, 235, 220));
        jLabel3.setText("Cake options");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(250, 80, 336, 50);

        jLabel9.setBackground(new java.awt.Color(179, 179, 230,60));
        jLabel9.setOpaque(true);
        getContentPane().add(jLabel9);
        jLabel9.setBounds(190, 50, 400, 110);

        jLabel6.setBackground(new java.awt.Color(239, 239, 251));
        jLabel6.setFont(new java.awt.Font("Castellar", 1, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(101, 58, 15));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Toppings");
        jLabel6.setOpaque(true);
        getContentPane().add(jLabel6);
        jLabel6.setBounds(30, 360, 150, 40);

        buttonGroup1.add(jRadioButton2);
        jRadioButton2.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 250, 243));
        jRadioButton2.setText("Vanilla");
        jRadioButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton2.setFocusable(false);
        jRadioButton2.setOpaque(false);
        getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(320, 290, 100, 27);

        buttonGroup1.add(jRadioButton1);
        jRadioButton1.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 250, 243));
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Chocolate");
        jRadioButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton1.setFocusable(false);
        jRadioButton1.setOpaque(false);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(190, 290, 130, 27);

        buttonGroup1.add(jRadioButton3);
        jRadioButton3.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(255, 250, 243));
        jRadioButton3.setText("Red Velvet");
        jRadioButton3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton3.setFocusable(false);
        jRadioButton3.setOpaque(false);
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(420, 290, 130, 27);

        buttonGroup1.add(jRadioButton4);
        jRadioButton4.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(255, 250, 243));
        jRadioButton4.setText("Lemon");
        jRadioButton4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jRadioButton4.setFocusable(false);
        jRadioButton4.setOpaque(false);
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jRadioButton4);
        jRadioButton4.setBounds(540, 290, 81, 27);

        jLabel4.setBackground(new java.awt.Color(179, 179, 230,80));
        jLabel4.setOpaque(true);
        getContentPane().add(jLabel4);
        jLabel4.setBounds(180, 280, 450, 40);

        jLabel5.setBackground(new java.awt.Color(239, 239, 251));
        jLabel5.setFont(new java.awt.Font("Castellar", 1, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(101, 58, 15));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Flavors");
        jLabel5.setOpaque(true);
        getContentPane().add(jLabel5);
        jLabel5.setBounds(30, 280, 150, 40);

        jCheckBox1.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 250, 243));
        jCheckBox1.setText("Sprinkles");
        jCheckBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCheckBox1.setFocusable(false);
        jCheckBox1.setOpaque(false);
        getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(180, 370, 110, 27);

        jCheckBox2.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(255, 250, 243));
        jCheckBox2.setText("Nuts");
        jCheckBox2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCheckBox2.setFocusable(false);
        jCheckBox2.setOpaque(false);
        getContentPane().add(jCheckBox2);
        jCheckBox2.setBounds(290, 370, 90, 27);

        jCheckBox4.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jCheckBox4.setForeground(new java.awt.Color(255, 250, 243));
        jCheckBox4.setText("Chocolate Chips");
        jCheckBox4.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCheckBox4.setFocusable(false);
        jCheckBox4.setOpaque(false);
        getContentPane().add(jCheckBox4);
        jCheckBox4.setBounds(370, 370, 180, 27);

        jCheckBox3.setFont(new java.awt.Font("Baskerville Old Face", 1, 18)); // NOI18N
        jCheckBox3.setForeground(new java.awt.Color(255, 250, 243));
        jCheckBox3.setText("Fruits");
        jCheckBox3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jCheckBox3.setFocusable(false);
        jCheckBox3.setOpaque(false);
        getContentPane().add(jCheckBox3);
        jCheckBox3.setBounds(540, 370, 71, 27);
        getContentPane().add(jLabel10);
        jLabel10.setBounds(-30, -80, 710, 310);

        jLabel7.setBackground(new java.awt.Color(179, 179, 230,80));
        jLabel7.setOpaque(true);
        getContentPane().add(jLabel7);
        jLabel7.setBounds(170, 360, 470, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/cakes.jpeg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(-60, 0, 850, 530);

        jLabel8.setBackground(new java.awt.Color(102, 0, 0,80));
        jLabel8.setOpaque(true);
        getContentPane().add(jLabel8);
        jLabel8.setBounds(180, 280, 440, 40);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
       ShoppingCart frame=new ShoppingCart();
       ModifyOrder.updateOrder();
       this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed

        double price=0;
        try(
            Connection connection=DriverManager.getConnection("jdbc:derby://localhost:1527/Cottege_Bakery ", "Bakery", "Bakery");
            Statement statement=connection.createStatement();
            ResultSet resultSet=statement.executeQuery("SELECT Pro_Price FROM Product WHERE Pro_ID="+(jComboBox1.getSelectedIndex()+1))
            ){
                while (resultSet.next()){
                    price=resultSet.getDouble(1);
                }
            }
        catch (SQLException e){
            JOptionPane.showMessageDialog(null, e, "DATABASE ERROR", JOptionPane.ERROR_MESSAGE);
        }
        this.setVisible(false);
        
        if(ShoppingCart.numOfItems==0){
            ShoppingCart.order.append("\n  "+cakes[jComboBox1.getSelectedIndex()]);}
        else{
            ShoppingCart.order.append("\n\n  "+cakes[jComboBox1.getSelectedIndex()]);
        }
        ShoppingCart.numOfItems++;
        
        if (jRadioButton1.isSelected()){
            flavor=jRadioButton1.getText();
        }
        else if(jRadioButton2.isSelected()){
            flavor=jRadioButton2.getText();
        }
        else if(jRadioButton3.isSelected()){
            flavor=jRadioButton3.getText();
        }
        else if(jRadioButton4.isSelected()){
            flavor=jRadioButton4.getText();
        }
        toppings="";
        if (jCheckBox1.isSelected()){
            toppings+=jCheckBox1.getText();
        }
        if (jCheckBox2.isSelected()){
            if(jCheckBox1.isSelected()){
            toppings+=", "+jCheckBox2.getText();}
            else{
                toppings+=jCheckBox2.getText();
            }
        }
        if (jCheckBox3.isSelected()){
            if(jCheckBox1.isSelected()||jCheckBox2.isSelected()){
            toppings+=", "+jCheckBox3.getText();}
            else{
                toppings+=jCheckBox3.getText();
            }
        }
        if (jCheckBox4.isSelected()){
            if(jCheckBox1.isSelected()||jCheckBox2.isSelected()||jCheckBox3.isSelected()){
            toppings+=", "+jCheckBox4.getText();}
            else{
                toppings+=jCheckBox4.getText();
            }
        }
        ShoppingCart.total+=price;
        ShoppingCart.orderList.add(new Orders(Orders.numberOfOrders+1, cakes[jComboBox1.getSelectedIndex()], flavor, toppings, price));
        ShoppingCart.order.append(String.format("%n      Flavor: %-8s                                                %.2f SR%n      Toppings: %-8s ",flavor,price,toppings));
        
        Order o=new Order();
        o.setVisible(true);
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        Order o=new Order();
        o.setVisible(true);
        
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jComboBox1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cake.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cake().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.ButtonGroup buttonGroup1;
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    // End of variables declaration//GEN-END:variables
}
