/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.sql.*;
import java.util.Properties;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.mail.*;  
import javax.mail.internet.*; 
/**
 *
 * @author Dana
 */
public class Delete_emp extends javax.swing.JFrame {
    

    /**
     * Creates new form Delete_emp
     */
    public Delete_emp() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        javax.swing.JLabel jLabel2 = new javax.swing.JLabel();
        idTextField = new javax.swing.JTextField();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        sendButton = new javax.swing.JButton();
        javax.swing.JButton backButton = new javax.swing.JButton();
        javax.swing.JLabel jLabel1 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("Delete Emplyee");
        getContentPane().setLayout(null);

        jLabel2.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(102, 51, 0));
        jLabel2.setText("To send it to the emplyee:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(300, 230, 410, 25);

        idTextField.setBackground(new java.awt.Color(255, 250, 243));
        idTextField.setFont(new java.awt.Font("Stencil", 0, 16)); // NOI18N
        idTextField.setForeground(new java.awt.Color(101, 58, 15));
        idTextField.setHorizontalAlignment(javax.swing.JTextField.CENTER);
        idTextField.setText("Enter Employee ID here");
        idTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(101, 58, 15), 3, true));
        idTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                idTextFieldActionPerformed(evt);
            }
        });
        getContentPane().add(idTextField);
        idTextField.setBounds(340, 120, 280, 40);

        jLabel3.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 51, 0));
        jLabel3.setText("Delete Employee ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(370, 50, 240, 25);

        jLabel4.setFont(new java.awt.Font("Stencil", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(102, 51, 0));
        jLabel4.setText("Write the cause of Deletion  ");
        getContentPane().add(jLabel4);
        jLabel4.setBounds(280, 200, 410, 25);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(255, 250, 243));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Serif", 0, 18)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(101, 58, 15));
        jTextArea1.setLineWrap(true);
        jTextArea1.setRows(5);
        jTextArea1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(101, 58, 15), 3, true));
        jScrollPane1.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(220, 270, 520, 290);

        sendButton.setBackground(new java.awt.Color(255, 250, 243));
        sendButton.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        sendButton.setForeground(new java.awt.Color(101, 58, 15));
        sendButton.setText("SEND");
        sendButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(101, 58, 15), 3, true));
        sendButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                sendButtonActionPerformed(evt);
            }
        });
        getContentPane().add(sendButton);
        sendButton.setBounds(440, 580, 93, 29);

        backButton.setBackground(new java.awt.Color(255, 250, 243));
        backButton.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        backButton.setForeground(new java.awt.Color(101, 58, 15));
        backButton.setText("Back");
        backButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(101, 58, 15), 3, true));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton);
        backButton.setBounds(40, 600, 90, 40);

        jLabel1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/back2.jpg"))); // NOI18N
        jLabel1.setText("jLabel1");
        getContentPane().add(jLabel1);
        jLabel1.setBounds(0, 0, 1000, 670);

        setBounds(0, 0, 1021, 722);
    }// </editor-fold>//GEN-END:initComponents

    private void sendButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_sendButtonActionPerformed
        // TODO add your handling code here:
        int EID ;
        boolean check=true ;
        for(int i=0 ; i<idTextField.getText().length() ; i++){ 
            if(!Character.isDigit(idTextField.getText().charAt(i)))
            {check = false; break;}
            }
        try(
            Connection connection = DriverManager.getConnection("jdbc:derby://localhost:1527/Cottege_Bakery", "Bakery", "Bakery");
            Statement st1 = connection.createStatement();
            Statement st2 = connection.createStatement(); 
            Statement st3 = connection.createStatement();)
            
        {
            if(!"".equals(idTextField.getText()))
            {
                if(check){
                    
                    EID = Integer.parseInt(idTextField.getText());
                    ResultSet emp_mail = st1.executeQuery("SELECT * FROM EMPLOYEE WHERE EMPLOYEE_ID = " + EID);
                    int delete_ACC = st2.executeUpdate("DELETE FROM EMPLOYEE_ACCOUNT WHERE EID = " + EID);
                    int delete_INFO = st3.executeUpdate("DELETE FROM EMPLOYEE WHERE EMPLOYEE_ID = " + EID);
                    
                    if(emp_mail.next() && delete_ACC == 1 && delete_INFO == 1)
                    {
                        String host="smtp.gmail.com";  
                        final String user="cottagebakery.java@gmail.com";  
                        final String password="cottage.123321";
                        String to = emp_mail.getString("MAIL");
                        Properties props = new Properties(); 
        props.put("mail.smtp.auth", "true");  
        props.put("mail.smtp.starttls.enable", "true");
        props.put("mail.smtp.host",host);    
        props.put("mail.smtp.port", "587");
        Session session = Session.getDefaultInstance(props,  
         new javax.mail.Authenticator() {  
           protected PasswordAuthentication getPasswordAuthentication() {  
         return new PasswordAuthentication(user,password);  
           }  
         });
        try {  
                MimeMessage message = new MimeMessage(session);  
                message.setFrom(new InternetAddress(user));  
                message.addRecipient(Message.RecipientType.TO,new InternetAddress(to));  
                message.setSubject("Cottage Bakery - Discharge");  
                message.setText(jTextArea1.getText()) ;  

               //send the message  
                Transport.send(message);  

     } catch (MessagingException e) {e.printStackTrace();} 
                        
                    }
                    JOptionPane.showMessageDialog(this,"Employee Deleted successfully !");
                    jTextArea1.setText("");
                    idTextField.setText("");
                    jTextArea1.setEditable(false);
                }
                else
                {
                    JOptionPane.showMessageDialog(this,"Please enter employee ID(ONLY DIGITS) !");
                }
            }else{JOptionPane.showMessageDialog(this,"Please enter valid employee ID !");}
        
        } 
        catch (SQLException ex) {
            Logger.getLogger(Delete_emp.class.getName()).log(Level.SEVERE, null, ex);
        }
    }//GEN-LAST:event_sendButtonActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ManagerOption().setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed

    private void idTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_idTextFieldActionPerformed
        // TODO add your handling code here:
        jTextArea1.setEditable(true);
    }//GEN-LAST:event_idTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Delete_emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Delete_emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Delete_emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Delete_emp.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Delete_emp().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JTextField idTextField;
    javax.swing.JScrollPane jScrollPane1;
    javax.swing.JTextArea jTextArea1;
    javax.swing.JButton sendButton;
    // End of variables declaration//GEN-END:variables
}
