/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import project.Manager;
import project.ManagerOption;
import project.Project;

/**
 *
 * @author Dana
 */
public class Emp_Info extends javax.swing.JFrame {

   Manager manager = Project.getManager();
    public Emp_Info() {
        initComponents();
        this.setVisible(true);
        this.setSize(850,565);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        emp_InfoTextArea = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel3 = new javax.swing.JLabel();
        javax.swing.JScrollPane jScrollPane2 = new javax.swing.JScrollPane();
        EIDTextArea = new javax.swing.JTextArea();
        backButton = new javax.swing.JButton();
        javax.swing.JPanel jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        emp_infoTextField = new javax.swing.JTextField();
        searchButton1 = new javax.swing.JButton();
        resetButton = new javax.swing.JButton();
        searchButton2 = new javax.swing.JButton();
        javax.swing.JLabel jLabel4 = new javax.swing.JLabel();
        javax.swing.JLabel jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        emp_InfoTextArea.setEditable(false);
        emp_InfoTextArea.setBackground(new java.awt.Color(255, 250, 243));
        emp_InfoTextArea.setColumns(20);
        emp_InfoTextArea.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        emp_InfoTextArea.setForeground(new java.awt.Color(101, 58, 15));
        emp_InfoTextArea.setRows(5);
        emp_InfoTextArea.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(101, 58, 15), 3, true));
        jScrollPane1.setViewportView(emp_InfoTextArea);

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(350, 50, 420, 200);

        jLabel2.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(101, 58, 15));
        jLabel2.setText("Employee Informations:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(350, 20, 237, 19);

        jLabel3.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(101, 58, 15));
        jLabel3.setText("Employee ID's: ");
        getContentPane().add(jLabel3);
        jLabel3.setBounds(350, 260, 160, 19);

        EIDTextArea.setEditable(false);
        EIDTextArea.setBackground(new java.awt.Color(255, 250, 243));
        EIDTextArea.setColumns(20);
        EIDTextArea.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        EIDTextArea.setForeground(new java.awt.Color(101, 58, 15));
        EIDTextArea.setRows(5);
        EIDTextArea.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(101, 58, 15), 3, true));
        jScrollPane2.setViewportView(EIDTextArea);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(350, 300, 420, 186);

        backButton.setBackground(new java.awt.Color(255, 250, 243));
        backButton.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        backButton.setForeground(new java.awt.Color(101, 58, 15));
        backButton.setText("Back");
        backButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(101, 58, 15), 3, true));
        backButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                backButtonActionPerformed(evt);
            }
        });
        getContentPane().add(backButton);
        backButton.setBounds(20, 460, 95, 25);

        jPanel1.setBackground(new java.awt.Color(102, 51, 0,80));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("To search Employee Informations");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(10, 40, 270, 32);

        emp_infoTextField.setBackground(new java.awt.Color(255, 250, 243));
        emp_infoTextField.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        emp_infoTextField.setForeground(new java.awt.Color(101, 58, 15));
        emp_infoTextField.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(101, 58, 15), 3, true));
        jPanel1.add(emp_infoTextField);
        emp_infoTextField.setBounds(33, 90, 230, 45);

        searchButton1.setBackground(new java.awt.Color(255, 250, 243));
        searchButton1.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        searchButton1.setForeground(new java.awt.Color(101, 58, 15));
        searchButton1.setText("Search");
        searchButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(101, 58, 15), 3, true));
        searchButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(searchButton1);
        searchButton1.setBounds(30, 170, 107, 25);

        resetButton.setBackground(new java.awt.Color(255, 250, 243));
        resetButton.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        resetButton.setForeground(new java.awt.Color(101, 58, 15));
        resetButton.setText("Reset");
        resetButton.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(101, 58, 15), 3, true));
        resetButton.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                resetButtonActionPerformed(evt);
            }
        });
        jPanel1.add(resetButton);
        resetButton.setBounds(160, 170, 107, 25);

        searchButton2.setBackground(new java.awt.Color(255, 250, 243));
        searchButton2.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        searchButton2.setForeground(new java.awt.Color(101, 58, 15));
        searchButton2.setText("Search");
        searchButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(101, 58, 15), 3, true));
        searchButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                searchButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(searchButton2);
        searchButton2.setBounds(90, 320, 101, 40);

        jLabel4.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("To search Employee ID's");
        jPanel1.add(jLabel4);
        jLabel4.setBounds(30, 270, 270, 24);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 40, 300, 400);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/back2.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 850, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void searchButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButton1ActionPerformed
       
        if((!emp_infoTextField.getText().equals("")))
        {
             
             boolean isDigit = true ;
             for(int i = 0 ; i< emp_infoTextField.getText().length() ; i++  )
             {
                if(!Character.isDigit(emp_infoTextField.getText().charAt(i)))
                {isDigit = false; 
                break;}
             }
             
            if(isDigit){
                int EID = Integer.parseInt(emp_infoTextField.getText());
                try(Connection connection = DriverManager.getConnection("jdbc:derby://localhost:1527/Cottege_Bakery", "Bakery", "Bakery");
                Statement st = connection.createStatement() ;)
            {
             ResultSet eRs = st.executeQuery("SELECT * FROM EMPLOYEE WHERE EMPLOYEE_ID = " + EID +" AND MAG_ID IS NOT NULL");
             if(eRs.next())
             
             {emp_InfoTextArea.setText("Employee ID: " + eRs.getInt(1) +"\nFirst Name: " +eRs.getString(2)+"\nLast Name: " +eRs.getString(3)
                         +"\nHours: "+ eRs.getDouble(4) +"\nAddress: "+eRs.getString(5) + "\nAge: " +  eRs.getInt(6) +"\n Salary: "
                         +eRs.getDouble(7)+"\nMail: "+eRs.getString(8)+"\nManager ID: "+ eRs.getInt(9) ); }
             else { JOptionPane.showMessageDialog(this, " There is no employee with this ID please enter valid employee ID");}
             
             eRs.close();
             
                     } 
            catch (SQLException ex) {
                Logger.getLogger(Emp_Info.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
            else{ JOptionPane.showMessageDialog(this, "Enter employee ID (Only Digits) please");}
        }
        else {
            JOptionPane.showMessageDialog(this, "Enter employee ID please");
            
        }
    }//GEN-LAST:event_searchButton1ActionPerformed

    private void resetButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_resetButtonActionPerformed
        // TODO add your handling code here:
        emp_InfoTextArea.setText("");
        EIDTextArea.setText(""); 
        emp_infoTextField.setText("");
        
    }//GEN-LAST:event_resetButtonActionPerformed

    private void searchButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_searchButton2ActionPerformed
        // TODO add your handling code here:
        try(Connection connection2 = DriverManager.getConnection("jdbc:derby://localhost:1527/Cottege_Bakery", "Bakery", "Bakery");
                Statement st2 = connection2.createStatement() ;)
        {
            String ids = "";
            ResultSet rs = st2.executeQuery("SELECT EMPLOYEE_ID FROM EMPLOYEE WHERE MAG_ID IS NOT NULL");
            while(rs.next())
            {
                ids = ids + "\n" + rs.getInt(1)+"\n";
            }
            EIDTextArea.setText("Number of Employee is: "+manager.getNumOfEmployee()+"\nEmployee ID's: " + ids);
            
        } 
        catch (SQLException ex) {
            Logger.getLogger(Emp_Info.class.getName()).log(Level.SEVERE, null, ex);
        }
        
    }//GEN-LAST:event_searchButton2ActionPerformed

    private void backButtonActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_backButtonActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new ManagerOption().setVisible(true);
    }//GEN-LAST:event_backButtonActionPerformed
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Emp_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Emp_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Emp_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Emp_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Emp_Info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JTextArea EIDTextArea;
    javax.swing.JButton backButton;
    javax.swing.JTextArea emp_InfoTextArea;
    javax.swing.JTextField emp_infoTextField;
    javax.swing.JLabel jLabel1;
    javax.swing.JLabel jLabel2;
    javax.swing.JScrollPane jScrollPane1;
    javax.swing.JButton resetButton;
    javax.swing.JButton searchButton1;
    javax.swing.JButton searchButton2;
    // End of variables declaration//GEN-END:variables
}
