/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.awt.Color;
import javax.swing.JFrame;
import project.Orders;
import project.ShoppingCart;

/**
 *
 * @author Haya alzahim
 */
public class ModifyOrder extends javax.swing.JFrame {
ShoppingCart f=new ShoppingCart();
static Orders modifiedPro;


    /**
     * Creates new form ModifyOrder
     */
    public ModifyOrder() {f.setVisible(false);
        initComponents();
        f.setVisible(false);
       getContentPane().setBackground(new Color(243,235,220));
       this.setSize(670,350);
       this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
       this.setVisible(true);
       
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jFrame1 = new javax.swing.JFrame();
        jLabel3 = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jRadioButton1 = new javax.swing.JRadioButton();
        jRadioButton2 = new javax.swing.JRadioButton();
        jRadioButton3 = new javax.swing.JRadioButton();
        jLabel8 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jCheckBox1 = new javax.swing.JCheckBox();
        jCheckBox2 = new javax.swing.JCheckBox();
        jCheckBox4 = new javax.swing.JCheckBox();
        jCheckBox3 = new javax.swing.JCheckBox();
        jLabel4 = new javax.swing.JLabel();
        jButton5 = new javax.swing.JButton();
        jFrame2 = new javax.swing.JFrame();
        jLabel9 = new javax.swing.JLabel();
        jLabel10 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jRadioButton4 = new javax.swing.JRadioButton();
        jRadioButton5 = new javax.swing.JRadioButton();
        jRadioButton6 = new javax.swing.JRadioButton();
        jLabel12 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        jCheckBox5 = new javax.swing.JCheckBox();
        jCheckBox6 = new javax.swing.JCheckBox();
        jCheckBox7 = new javax.swing.JCheckBox();
        jCheckBox8 = new javax.swing.JCheckBox();
        jLabel14 = new javax.swing.JLabel();
        jButton6 = new javax.swing.JButton();
        jLabel15 = new javax.swing.JLabel();
        jLabel16 = new javax.swing.JLabel();
        jComboBox1 = new javax.swing.JComboBox<>();
        jLabel17 = new javax.swing.JLabel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jButton9 = new javax.swing.JButton();

        jFrame1.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame1.setBackground(new java.awt.Color(243, 235, 220));
        jFrame1.getContentPane().setLayout(null);
        jFrame1.getContentPane().add(jLabel3);
        jLabel3.setBounds(-20, 10, 170, 130);

        jLabel5.setFont(new java.awt.Font("Palatino Linotype", 0, 24)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(101, 58, 15));
        jLabel5.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel5.setText("Modify Order");
        jFrame1.getContentPane().add(jLabel5);
        jLabel5.setBounds(230, 50, 215, 40);

        jLabel7.setFont(new java.awt.Font("Palatino Linotype", 0, 24)); // NOI18N
        jLabel7.setForeground(new java.awt.Color(101, 58, 15));
        jLabel7.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel7.setText("Flavors");
        jFrame1.getContentPane().add(jLabel7);
        jLabel7.setBounds(80, 140, 109, 40);

        jRadioButton1.setFont(new java.awt.Font("Roboto Slab SemiBold", 0, 14)); // NOI18N
        jRadioButton1.setForeground(new java.awt.Color(255, 250, 243));
        jRadioButton1.setSelected(true);
        jRadioButton1.setText("Classic");
        jRadioButton1.setFocusPainted(false);
        jRadioButton1.setOpaque(false);
        jRadioButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton1ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jRadioButton1);
        jRadioButton1.setBounds(210, 150, 93, 27);

        jRadioButton2.setFont(new java.awt.Font("Roboto Slab SemiBold", 0, 14)); // NOI18N
        jRadioButton2.setForeground(new java.awt.Color(255, 250, 243));
        jRadioButton2.setText("Chocolate");
        jRadioButton2.setOpaque(false);
        jRadioButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton2ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jRadioButton2);
        jRadioButton2.setBounds(330, 150, 100, 27);

        jRadioButton3.setFont(new java.awt.Font("Roboto Slab SemiBold", 0, 14)); // NOI18N
        jRadioButton3.setForeground(new java.awt.Color(255, 250, 243));
        jRadioButton3.setText("Red Velvet");
        jRadioButton3.setOpaque(false);
        jRadioButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton3ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jRadioButton3);
        jRadioButton3.setBounds(450, 150, 95, 27);

        jLabel8.setBackground(new java.awt.Color(102, 51, 0,80));
        jLabel8.setOpaque(true);
        jFrame1.getContentPane().add(jLabel8);
        jLabel8.setBounds(210, 150, 410, 30);

        jLabel6.setFont(new java.awt.Font("Palatino Linotype", 0, 24)); // NOI18N
        jLabel6.setForeground(new java.awt.Color(101, 58, 15));
        jLabel6.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel6.setText("Toppings");
        jFrame1.getContentPane().add(jLabel6);
        jLabel6.setBounds(80, 190, 120, 40);

        jCheckBox1.setFont(new java.awt.Font("Roboto Slab SemiBold", 0, 14)); // NOI18N
        jCheckBox1.setForeground(new java.awt.Color(255, 250, 243));
        jCheckBox1.setText("Sprinkles");
        jCheckBox1.setOpaque(false);
        jCheckBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox1ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jCheckBox1);
        jCheckBox1.setBounds(210, 200, 83, 27);

        jCheckBox2.setFont(new java.awt.Font("Roboto Slab SemiBold", 0, 14)); // NOI18N
        jCheckBox2.setForeground(new java.awt.Color(255, 250, 243));
        jCheckBox2.setText("Nuts");
        jCheckBox2.setOpaque(false);
        jFrame1.getContentPane().add(jCheckBox2);
        jCheckBox2.setBounds(310, 200, 53, 27);

        jCheckBox4.setFont(new java.awt.Font("Roboto Slab SemiBold", 0, 14)); // NOI18N
        jCheckBox4.setForeground(new java.awt.Color(255, 250, 243));
        jCheckBox4.setText("Chocolate Chips");
        jCheckBox4.setOpaque(false);
        jFrame1.getContentPane().add(jCheckBox4);
        jCheckBox4.setBounds(400, 200, 129, 27);

        jCheckBox3.setFont(new java.awt.Font("Roboto Slab SemiBold", 0, 14)); // NOI18N
        jCheckBox3.setForeground(new java.awt.Color(255, 250, 243));
        jCheckBox3.setText("Fruits");
        jCheckBox3.setOpaque(false);
        jCheckBox3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox3ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jCheckBox3);
        jCheckBox3.setBounds(540, 200, 61, 27);

        jLabel4.setBackground(new java.awt.Color(102, 51, 0,80));
        jLabel4.setOpaque(true);
        jFrame1.getContentPane().add(jLabel4);
        jLabel4.setBounds(210, 200, 410, 30);

        jButton5.setBackground(new java.awt.Color(243, 235, 220));
        jButton5.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jButton5.setForeground(new java.awt.Color(102, 51, 0));
        jButton5.setText("Confirm");
        jButton5.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton5ActionPerformed(evt);
            }
        });
        jFrame1.getContentPane().add(jButton5);
        jButton5.setBounds(290, 260, 110, 30);

        jFrame2.setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        jFrame2.setBackground(new java.awt.Color(243, 235, 220));
        jFrame2.getContentPane().setLayout(null);
        jFrame2.getContentPane().add(jLabel9);
        jLabel9.setBounds(-20, 10, 170, 130);

        jLabel10.setFont(new java.awt.Font("Palatino Linotype", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(101, 58, 15));
        jLabel10.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel10.setText("Modify Order");
        jFrame2.getContentPane().add(jLabel10);
        jLabel10.setBounds(230, 50, 215, 40);

        jLabel11.setFont(new java.awt.Font("Palatino Linotype", 0, 24)); // NOI18N
        jLabel11.setForeground(new java.awt.Color(101, 58, 15));
        jLabel11.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel11.setText("Flavors");
        jFrame2.getContentPane().add(jLabel11);
        jLabel11.setBounds(80, 140, 109, 40);

        jRadioButton4.setFont(new java.awt.Font("Roboto Slab SemiBold", 0, 14)); // NOI18N
        jRadioButton4.setForeground(new java.awt.Color(255, 250, 243));
        jRadioButton4.setSelected(true);
        jRadioButton4.setText("Classic");
        jRadioButton4.setFocusPainted(false);
        jRadioButton4.setOpaque(false);
        jRadioButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton4ActionPerformed(evt);
            }
        });
        jFrame2.getContentPane().add(jRadioButton4);
        jRadioButton4.setBounds(210, 150, 93, 27);

        jRadioButton5.setFont(new java.awt.Font("Roboto Slab SemiBold", 0, 14)); // NOI18N
        jRadioButton5.setForeground(new java.awt.Color(255, 250, 243));
        jRadioButton5.setText("Chocolate");
        jRadioButton5.setOpaque(false);
        jRadioButton5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton5ActionPerformed(evt);
            }
        });
        jFrame2.getContentPane().add(jRadioButton5);
        jRadioButton5.setBounds(330, 150, 100, 27);

        jRadioButton6.setFont(new java.awt.Font("Roboto Slab SemiBold", 0, 14)); // NOI18N
        jRadioButton6.setForeground(new java.awt.Color(255, 250, 243));
        jRadioButton6.setText("Red Velvet");
        jRadioButton6.setOpaque(false);
        jRadioButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jRadioButton6ActionPerformed(evt);
            }
        });
        jFrame2.getContentPane().add(jRadioButton6);
        jRadioButton6.setBounds(450, 150, 95, 27);

        jLabel12.setBackground(new java.awt.Color(102, 51, 0,80));
        jLabel12.setOpaque(true);
        jFrame2.getContentPane().add(jLabel12);
        jLabel12.setBounds(210, 150, 410, 30);

        jLabel13.setFont(new java.awt.Font("Palatino Linotype", 0, 24)); // NOI18N
        jLabel13.setForeground(new java.awt.Color(101, 58, 15));
        jLabel13.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel13.setText("Toppings");
        jFrame2.getContentPane().add(jLabel13);
        jLabel13.setBounds(80, 190, 120, 40);

        jCheckBox5.setFont(new java.awt.Font("Roboto Slab SemiBold", 0, 14)); // NOI18N
        jCheckBox5.setForeground(new java.awt.Color(255, 250, 243));
        jCheckBox5.setText("Sprinkles");
        jCheckBox5.setOpaque(false);
        jCheckBox5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox5ActionPerformed(evt);
            }
        });
        jFrame2.getContentPane().add(jCheckBox5);
        jCheckBox5.setBounds(210, 200, 83, 27);

        jCheckBox6.setFont(new java.awt.Font("Roboto Slab SemiBold", 0, 14)); // NOI18N
        jCheckBox6.setForeground(new java.awt.Color(255, 250, 243));
        jCheckBox6.setText("Nuts");
        jCheckBox6.setOpaque(false);
        jFrame2.getContentPane().add(jCheckBox6);
        jCheckBox6.setBounds(310, 200, 53, 27);

        jCheckBox7.setFont(new java.awt.Font("Roboto Slab SemiBold", 0, 14)); // NOI18N
        jCheckBox7.setForeground(new java.awt.Color(255, 250, 243));
        jCheckBox7.setText("Chocolate Chips");
        jCheckBox7.setOpaque(false);
        jFrame2.getContentPane().add(jCheckBox7);
        jCheckBox7.setBounds(400, 200, 129, 27);

        jCheckBox8.setFont(new java.awt.Font("Roboto Slab SemiBold", 0, 14)); // NOI18N
        jCheckBox8.setForeground(new java.awt.Color(255, 250, 243));
        jCheckBox8.setText("Fruits");
        jCheckBox8.setOpaque(false);
        jCheckBox8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jCheckBox8ActionPerformed(evt);
            }
        });
        jFrame2.getContentPane().add(jCheckBox8);
        jCheckBox8.setBounds(540, 200, 61, 27);

        jLabel14.setBackground(new java.awt.Color(102, 51, 0,80));
        jLabel14.setOpaque(true);
        jFrame2.getContentPane().add(jLabel14);
        jLabel14.setBounds(210, 200, 410, 30);

        jButton6.setBackground(new java.awt.Color(243, 235, 220));
        jButton6.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jButton6.setForeground(new java.awt.Color(102, 51, 0));
        jButton6.setText("Confirm");
        jButton6.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton6ActionPerformed(evt);
            }
        });
        jFrame2.getContentPane().add(jButton6);
        jButton6.setBounds(290, 260, 110, 30);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setBackground(new java.awt.Color(243, 235, 220));
        getContentPane().setLayout(null);

        jLabel15.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jLabel15.setForeground(new java.awt.Color(101, 58, 15));
        jLabel15.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel15.setText("Which order would you like to modify?");
        getContentPane().add(jLabel15);
        jLabel15.setBounds(180, 120, 330, 40);
        getContentPane().add(jLabel16);
        jLabel16.setBounds(-20, 10, 170, 130);

        jComboBox1.setBackground(new java.awt.Color(255, 250, 243));
        jComboBox1.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jComboBox1.setForeground(new java.awt.Color(139, 78, 19));
        jComboBox1.setModel(new javax.swing.DefaultComboBoxModel<>(ShoppingCart.orderArray));
        jComboBox1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jComboBox1.setFocusable(false);
        jComboBox1.setLightWeightPopupEnabled(false);
        jComboBox1.setName(""); // NOI18N
        jComboBox1.setOpaque(false);
        jComboBox1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jComboBox1ActionPerformed(evt);
            }
        });
        getContentPane().add(jComboBox1);
        jComboBox1.setBounds(110, 180, 470, 50);

        jLabel17.setFont(new java.awt.Font("Palatino Linotype", 0, 24)); // NOI18N
        jLabel17.setForeground(new java.awt.Color(101, 58, 15));
        jLabel17.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel17.setText("Modify Order");
        getContentPane().add(jLabel17);
        jLabel17.setBounds(230, 50, 215, 40);

        jButton7.setBackground(new java.awt.Color(243, 235, 220));
        jButton7.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jButton7.setForeground(new java.awt.Color(102, 51, 0));
        jButton7.setText("Modify Item");
        jButton7.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton7.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton7.setFocusable(false);
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton7);
        jButton7.setBounds(340, 260, 130, 30);

        jButton8.setBackground(new java.awt.Color(243, 235, 220));
        jButton8.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jButton8.setForeground(new java.awt.Color(102, 51, 0));
        jButton8.setText("Remove Item");
        jButton8.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton8.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton8.setFocusable(false);
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton8);
        jButton8.setBounds(200, 260, 120, 30);

        jButton9.setBackground(new java.awt.Color(243, 235, 220));
        jButton9.setFont(new java.awt.Font("Palatino Linotype", 0, 18)); // NOI18N
        jButton9.setForeground(new java.awt.Color(102, 51, 0));
        jButton9.setText("Back");
        jButton9.setToolTipText("To go to the previous page");
        jButton9.setBorder(javax.swing.BorderFactory.createBevelBorder(javax.swing.border.BevelBorder.RAISED));
        jButton9.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton9.setFocusable(false);
        jButton9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton9ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton9);
        jButton9.setBounds(20, 260, 110, 30);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jRadioButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton1ActionPerformed

    private void jRadioButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton2ActionPerformed

    private void jRadioButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton3ActionPerformed

    private void jCheckBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox1ActionPerformed

    private void jCheckBox3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox3ActionPerformed

    private void jButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton5ActionPerformed

    private void jRadioButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton4ActionPerformed

    private void jRadioButton5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton5ActionPerformed

    private void jRadioButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jRadioButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jRadioButton6ActionPerformed

    private void jCheckBox5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox5ActionPerformed

    private void jCheckBox8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jCheckBox8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jCheckBox8ActionPerformed

    private void jButton6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jButton6ActionPerformed

    private void jComboBox1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jComboBox1ActionPerformed
        // TODO add your handling code here:
        String modifiedName=ShoppingCart.orderList.get(jComboBox1.getSelectedIndex()).getProductName();
        if(modifiedName.equals("Croissant Plain")||modifiedName.equals("Croissant Zatar")||modifiedName.equals("Croissant Chedder")||modifiedName.equals("Croissant Phili Cheese")||modifiedName.equals("Garlic Bread")||modifiedName.equals("White Toast")||modifiedName.equals("Brown Toast")||modifiedName.equals("Sandwich")){
            jButton7.setEnabled(false);
        }
        else{
            jButton7.setEnabled(true);
        }
        
    }//GEN-LAST:event_jComboBox1ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        modifiedPro=ShoppingCart.orderList.get(jComboBox1.getSelectedIndex());
        String modifiedName=modifiedPro.getProductName();
        if(modifiedName.equals("Cheesecake")||modifiedName.equals("Naked cake")||modifiedName.equals("Sponge cake")){
            CakeModify c=new CakeModify();
        }
        else if (modifiedName.equals("Yeast Donuts")||modifiedName.equals("Donut Holes")||modifiedName.equals("Filled Donuts")||modifiedName.equals("Long johns Donuts")){
            DonutModify d=new DonutModify();
        }
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        ShoppingCart.orderList.remove(jComboBox1.getSelectedIndex());
        updateOrder();
        
        this.setVisible(false);
        f.setVisible(true);
    }//GEN-LAST:event_jButton8ActionPerformed

    private void jButton9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton9ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        ShoppingCart o=new ShoppingCart();
        ModifyOrder.updateOrder();
        
    }//GEN-LAST:event_jButton9ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(ModifyOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(ModifyOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(ModifyOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(ModifyOrder.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new ModifyOrder().setVisible(true);
            }
        });
    }
    
    
    public static void updateOrder(){
    ShoppingCart.total=0.0;
    ShoppingCart.order.setLength(0);
    for (int i=0; i<ShoppingCart.orderList.size(); i++){
        if(i==0){
        ShoppingCart.order.append(ShoppingCart.orderList.get(i).getProductName());}
        else{
            ShoppingCart.order.append("\n\n"+ShoppingCart.orderList.get(i).getProductName());
        }
        
        ShoppingCart.total+=ShoppingCart.orderList.get(i).getPrice();
        String proName=ShoppingCart.orderList.get(i).getProductName();
        if(proName.equals("Croissant Plain")||proName.equals("Croissant Zatar")||proName.equals("Croissant Chedder")||proName.equals("Croissant Phili Cheese")||proName.equals("Garlic Bread")||proName.equals("White Toast")||proName.equals("Brown Toast")||proName.equals("Sandwich")){
        ShoppingCart.order.append(String.format("                                                   %.2f SR ",ShoppingCart.orderList.get(i).getPrice()));
        }
            else{
            ShoppingCart.order.append(String.format("%n   Flavor: %s                                                %.2f SR%n   Toppings: %s ",ShoppingCart.orderList.get(i).getFlavor(),ShoppingCart.orderList.get(i).getPrice(),ShoppingCart.orderList.get(i).getToppings()));}
    }

        ShoppingCart.jTextArea1.setText(ShoppingCart.order.toString());
        ShoppingCart.numOfItems=ShoppingCart.orderList.size();
        
        ShoppingCart.jLabel5.setText("( "+(ShoppingCart.orderList.size())+" Products)                            "+ShoppingCart.total+" SR");
       if(ShoppingCart.orderList.size()>0){
            ShoppingCart.checkOutButton.setVisible(true);
            ShoppingCart.editOrderButton.setVisible(true);
            ShoppingCart.jLabel8.setVisible(false);
        }
        else{
            ShoppingCart.jTextArea1.setText(String.format("%n%n%n%n\t   %s%n\t%s","Your basket is empty .","Start adding some pastries !"));
        }
        /*f.setVisible(true);
        f.setSize(640,449);
        f.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);*/
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JButton jButton9;
    private javax.swing.JCheckBox jCheckBox1;
    private javax.swing.JCheckBox jCheckBox2;
    private javax.swing.JCheckBox jCheckBox3;
    private javax.swing.JCheckBox jCheckBox4;
    private javax.swing.JCheckBox jCheckBox5;
    private javax.swing.JCheckBox jCheckBox6;
    private javax.swing.JCheckBox jCheckBox7;
    private javax.swing.JCheckBox jCheckBox8;
    private javax.swing.JComboBox<String> jComboBox1;
    private javax.swing.JFrame jFrame1;
    private javax.swing.JFrame jFrame2;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel12;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel15;
    private javax.swing.JLabel jLabel16;
    private javax.swing.JLabel jLabel17;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JRadioButton jRadioButton1;
    private javax.swing.JRadioButton jRadioButton2;
    private javax.swing.JRadioButton jRadioButton3;
    private javax.swing.JRadioButton jRadioButton4;
    private javax.swing.JRadioButton jRadioButton5;
    private javax.swing.JRadioButton jRadioButton6;
    // End of variables declaration//GEN-END:variables
}
