/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package project;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JFrame;
import javax.swing.JOptionPane;
import project.Orders;
import project.Orders;
import project.Project;
import project.Project;

/**
 *
 * @author 0204
 */
public class Or_Info extends javax.swing.JFrame {

  Customer cust ;
  Orders orders;
  
    public Or_Info() {
        initComponents();
        this.setVisible(true);
        this.setSize(868,554);
        this.setDefaultCloseOperation(JFrame.EXIT_ON_CLOSE);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane2 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();
        jLabel2 = new javax.swing.JLabel();
        jPanel1 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jTextField1 = new javax.swing.JTextField();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        label1 = new java.awt.Label();
        jButton4 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        getContentPane().setLayout(null);

        jTextArea1.setEditable(false);
        jTextArea1.setBackground(new java.awt.Color(255, 250, 243));
        jTextArea1.setColumns(20);
        jTextArea1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jTextArea1.setForeground(new java.awt.Color(101, 58, 15));
        jTextArea1.setRows(5);
        jTextArea1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(101, 58, 15), 3, true));
        jScrollPane2.setViewportView(jTextArea1);

        getContentPane().add(jScrollPane2);
        jScrollPane2.setBounds(340, 90, 480, 360);

        jLabel2.setFont(new java.awt.Font("Stencil", 0, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(101, 58, 15));
        jLabel2.setText("Order Informations:");
        getContentPane().add(jLabel2);
        jLabel2.setBounds(340, 50, 300, 25);

        jPanel1.setBackground(new java.awt.Color(102, 51, 0,80));
        jPanel1.setLayout(null);

        jLabel1.setFont(new java.awt.Font("Serif", 1, 18)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("To search Order Informations");
        jPanel1.add(jLabel1);
        jLabel1.setBounds(0, 60, 320, 32);

        jTextField1.setBackground(new java.awt.Color(255, 250, 243));
        jTextField1.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        jTextField1.setForeground(new java.awt.Color(101, 58, 15));
        jTextField1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(101, 58, 15), 3, true));
        jTextField1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jTextField1ActionPerformed(evt);
            }
        });
        jPanel1.add(jTextField1);
        jTextField1.setBounds(30, 130, 240, 50);

        jButton1.setBackground(new java.awt.Color(255, 250, 243));
        jButton1.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(101, 58, 15));
        jButton1.setText("Search");
        jButton1.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(101, 58, 15), 3, true));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton1);
        jButton1.setBounds(30, 260, 107, 25);

        jButton2.setBackground(new java.awt.Color(255, 250, 243));
        jButton2.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        jButton2.setForeground(new java.awt.Color(101, 58, 15));
        jButton2.setText("Reset");
        jButton2.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(101, 58, 15), 3, true));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        jPanel1.add(jButton2);
        jButton2.setBounds(170, 260, 107, 25);

        label1.setText("label1");
        jPanel1.add(label1);
        label1.setBounds(340, 30, 420, 340);

        getContentPane().add(jPanel1);
        jPanel1.setBounds(20, 40, 300, 400);

        jButton4.setBackground(new java.awt.Color(255, 250, 243));
        jButton4.setFont(new java.awt.Font("Stencil", 0, 18)); // NOI18N
        jButton4.setForeground(new java.awt.Color(101, 58, 15));
        jButton4.setText("Back");
        jButton4.setBorder(new javax.swing.border.LineBorder(new java.awt.Color(101, 58, 15), 3, true));
        jButton4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton4ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton4);
        jButton4.setBounds(15, 455, 95, 25);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/project/back2.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 0, 850, 510);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton4ActionPerformed
        // TODO add your handling code here:
        this.setVisible(false);
        new CustomerOption().setVisible(true);
    }//GEN-LAST:event_jButton4ActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
  cust = Project.getCustomer() ;
   if((!jTextField1.getText().equals("")))
        {

            boolean isDigit = true ;
            for(int i = 0 ; i< jTextField1.getText().length() ; i++  )
            {
                if(!Character.isDigit(jTextField1.getText().charAt(i)))
                {isDigit = false;
                    break;}
            }
        if(isDigit){
             int CID, ONumber;
             try(
                Connection connection = DriverManager.getConnection("jdbc:derby://localhost:1527/Cottege_Bakery", "Bakery", "Bakery");
                Statement st = connection.createStatement();
            ){
                ResultSet show;

                    int ordernumber ;
                    double price = 0;
                    String oname , flavor =" None " , toppings = "None";

                    CID = cust.getID();
                    ONumber = Integer.parseInt (jTextField1.getText());

                    show=st.executeQuery("SELECT ORDERS.ORDERNUMBER,PRO_NAME,FLAVOR,TOPPINGS,TOTALPRICE  from Orders , product , consist_of WHERE PRODUCT_ID=PRO_ID AND CONSIST_OF.ORDERNUMBER= ORDERS.ORDERNUMBER"
                            + " AND CUSTOMER_ID ="+ CID +" AND ORDERS.ORDERNUMBER =" + ONumber);
                   String txt="";
                   double total= 0;
                   while (show.next()){
               txt+="order number: "+show.getInt(1)+"\n Order name: "+show.getString(2)+"\nFlavor: "+show.getString(3)+"\nToppings: "+show.getString(4)+"\n";
               total= show.getDouble(5);   
               
                    }
                 txt+="\n Total price : "+total;
                 jTextArea1.setText(txt);         
//else { JOptionPane.showMessageDialog(this, " There is no Order with this number please enter valid Order number");}
                show.close();     
                    
                     } 
            catch (SQLException ex) {
                Logger.getLogger(Or_Info.class.getName()).log(Level.SEVERE, null, ex);
            }
            }
            else{ JOptionPane.showMessageDialog(this, "Enter Order number (Only Digits) please");}
        }
        else {
            JOptionPane.showMessageDialog(this, "Enter Order number please");
            
        }
                    
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
          jTextArea1.setText("");
       
        jTextField1.setText("");

    }//GEN-LAST:event_jButton2ActionPerformed

    private void jTextField1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jTextField1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_jTextField1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Or_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Or_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Or_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Or_Info.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Or_Info().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    javax.swing.JButton jButton1;
    javax.swing.JButton jButton2;
    javax.swing.JButton jButton4;
    javax.swing.JLabel jLabel1;
    javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel1;
    javax.swing.JScrollPane jScrollPane2;
    javax.swing.JTextArea jTextArea1;
    javax.swing.JTextField jTextField1;
    private java.awt.Label label1;
    // End of variables declaration//GEN-END:variables
}
